version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: ./etc/docker_files/Dockerfile 
    container_name: telegram-bot
    command:  poetry run python src/user_bot.py
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - bot-network


  admin_bot:
    build:
      context: .
      dockerfile: ./etc/docker_files/Dockerfile 
    container_name: admin-bot
    command:  poetry run python src/admin_bot.py
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - bot-network
  
  admin-ui:
    build:
      context: .
      dockerfile: ./etc/docker_files/Dockerfile 
    container_name: admin-ui
    command:  poetry run uvicorn src.admin_ui:app --host 0.0.0.0 --port 3000 --reload
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - bot-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 54322:5432
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
